export enum types {
    AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST",
    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS",
    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE",

    CREATE_MEMBER_REQUEST_REQUEST = 'CREATE_MEMBER_REQUEST_REQUEST',
    CREATE_MEMBER_REQUEST_SUCCESS = 'CREATE_MEMBER_REQUEST_SUCCESS',
    CREATE_MEMBER_REQUEST_FAILURE = 'CREATE_MEMBER_REQUEST_FAILURE',

    REGISTRATION_REQUEST = "REGISTRATION_REQUEST",
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",
    REGISTRATION_FAILURE = "REGISTRATION_FAILURE",

    BEGIN_API_CALL = "BEGIN_API_CALL",
    API_CALL_ERROR = "API_CALL_ERROR",
}